<?php

use Phalcon\Mvc\Url;

$url = new Url();
?>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $url->get();?>"><i class="fa fa-diamond"></i> File Manager</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li ><a href="<?php echo $url->get('');?>">Welcome </a></li>
                <li ><a href="<?php echo $url->get('manager/index');?>">File Manager </a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<?php echo $this->getContent(); ?>

<div class="row">
    <div class="col-lg-12">
        <p class="text-center -footer">
            <i class="fa fa-copyright"></i> 2016 | <a href="http://www.misterfeiszt.com" target="_blank">Tamas Feiszt</a>
        </p>
    </div>
</div>

